events {
    worker_connections 1024;
}

http {
    client_max_body_size 100M;

    client_body_timeout 60s;
    proxy_read_timeout 60s;
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;

    server {
        listen 80;
        server_name oqyrman.app www.oqyrman.app api.oqyrman.app admin.oqyrman.app;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name oqyrman.app www.oqyrman.app;

        ssl_certificate     /etc/letsencrypt/live/oqyrman.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/oqyrman.app/privkey.pem;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name api.oqyrman.app;

        ssl_certificate     /etc/letsencrypt/live/api.oqyrman.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.oqyrman.app/privkey.pem;

        location / {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name admin.oqyrman.app;

        ssl_certificate     /etc/letsencrypt/live/admin.oqyrman.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/admin.oqyrman.app/privkey.pem;

        location / {
            proxy_pass http://admin:3001;  # поменяйте порт под ваш контейнер
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}