events {}

http {
    server {
        listen 80;
        server_name oqyrman.app www.oqyrman.app api.oqyrman.app;
        return 301 https://$host$request_uri;
    }

    # server {
    #     listen 443 ssl;
    #     server_name oqyrman.app www.oqyrman.app;

        # ssl_certificate     /etc/letsencrypt/live/oqyrman.app/fullchain.pem;
        # ssl_certificate_key /etc/letsencrypt/live/oqyrman.app/privkey.pem;

    #     location / {
    #         proxy_pass http://frontend:3000;
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #     }
    # }

    server {
        listen 443 ssl;
        server_name api.oqyrman.app;

        ssl_certificate     /etc/letsencrypt/live/api.oqyrman.app/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.oqyrman.app/privkey.pem;

        location / {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}